[package]
name = "drone"
version = "0.1.0"
edition = "2021"
default-run = "drone"

[dependencies]
actix-files = { version = "=0.6.6", optional = true }
actix-web = { version = "=4.11.0", optional = true }
ctrlc = "=3.4.7"
serde = { version = "=1.0.219", features = ["derive"] }
serde_json = "=1.0.140"
serialport = { version = "=4.7.2", default-features = false, optional = true }
thiserror = "=2.0.12"
tokio = { version = "=1.45.0", features = [
    "net",
    "rt",
    "macros",
    "rt-multi-thread",
], optional = true }
tracing = "=0.1.41"
tracing-subscriber = "=0.3.19"

[lib]
path = "src/lib.rs"

[features]
default = ["real", "control_server"]
real = ["serialport"]
udp_server = ["tokio"]
control_server = ["udp_server", "actix-web", "actix-files"]
