[package]
name = "drone"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "=1.0.219", features = ["derive"] }
serde_json = "=1.0.140"
serialport = { version = "=4.7.2", default-features = false, optional = true }
thiserror = "=2.0.12"
tracing = "=0.1.41"
tracing-subscriber = "0.3.19"

[lib]
path = "src/lib.rs"

[features]
default = ["real"]
real = ["serialport"]
